# Generated by Django 5.2.5 on 2025-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=60)),
                ('size', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
